language: csharp
solution: Discord.Addons.WS4NetCompatibility.sln 

secure: "acvu67AEgbeQWvQT5385XLrLF1aD6eY3tE04SzVfrkfrJMlswLkD5Txvpvu6uPrqDD76UeYUA8vMPxLfJv36aNbOmdPFQaufVbXBtjwWjcHzyKi/NNS9MoPJSO7aVUc8v/XhSegJsLkVynqXiL3fRAPtmeemxu0wNlpzjVx2T3PLSLJU+Pdp4A6YwKZ4v+NVZ8XbcObcbz80g+itW+hyydZQZTofqAiZXEsnG0eebAHA8vh6ASZjVYaYispwEHQpwqh0ZjL0b66xERg5x0rm8G/n6hHVZhaniVFdXTaGPwlD8snKdn4zZE3qsijlK5TwFNh/K69gBHPUzJXp8o/D3he279ju2uS5W5GftVrLA1Wx6vAId05ag0AugLVln/+MhMg3YVRbUxZZ3G4Lio8lz3G5lP38Qlx9hjV4jLdjGpn4rPDI4FhXSXOyIoyISCzNXfDNTdieq3WgDrGKDd//YGXd78UzoxoIlyLhLBs10WWg9oSJfPAm3eDr0R7QqaJeysv1thUtylw5f/cTvwqU7vlILqIn+mm35JbNgmgwB1s08g1J/WDjoiUY10nzNYEhfGxERem5tDAel6lumC/lEFGYvnxO/OLuaixV0a/JP3zo4Iho3ZUqAI3mOcthFNcseKpP1AoJ+65wa8TbzGGW7zgV76SkmqHNIFMnVuy7pr4="

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003131
      mono: none
      env: DOTNETCORE=1

install:
  - dotnet restore

script:
  - dotnet pack src/Discord.Addons.WS4NetCompatibility --version-suffix $TRAVIS_BUILD_NUMBER -o artifacts
  - dotnet build src/ExampleProject

deploy:
  provider: script
  skip_cleanup: true
  script:
    - nuget push artifacts/*.nupkg $MYGET_API_KEY -Source https://www.myget.org/F/discord-net/api/v2/package